server {
    listen 80;
    server_name guillaumechampeau.com www.guillaumechampeau.com;

    root /usr/share/nginx/html;
    index index.html;

    location = /.well-known/matrix/server {
        default_type application/json;
        return 200 '{ "m.server": "matrix.guillaumechampeau.com:8448" }';
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
