server {
    listen 80;
    server_name guillaumechampeau.com www.guillaumechampeau.com;

    root /usr/share/nginx/html;
    index index.html;

    location = /.well-known/matrix/server {
        return 404;
    }

    location = /.well-known/matrix/client {
        return 404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
